
# This file controls the behavior of the Edge Functions runtime.
# For the top level configuration, see the Edge Functions documentation:
# https://supabase.com/docs/guides/functions/edge-functions

project_id = "dihdiemqnmalievpvqfh"

[functions.portfolio-analysis]
verify_jwt = true

[functions.seed-data]
verify_jwt = true

[functions.zerodha-exchange-token]
verify_jwt = false

[functions.zerodha-login-url]
verify_jwt = false

[functions.zerodha-logout]
verify_jwt = true

[functions.zerodha-portfolio]
verify_jwt = true
